---
parserOptions:
  sourceType: module

env:
  amd: true
  browser: true
  es6: true
  jquery: true
  node: true
  jest: true

extends:
 - airbnb

rules:
  import/extensions:
    - off
    - never
  import/no-extraneous-dependencies:
    - error
    - devDependencies: true
