export default (sequelize, DataTypes) => {
  const preEnrolled = sequelize.define('pre_inscritos', {
    cpf: {
      type: DataTypes.INTEGER,
      autoIncrement: false,
      primaryKey: true,
    },
    ra: DataTypes.INTEGER,
    nome: DataTypes.STRING,
    codigo_acompanhamento: DataTypes.INTEGER,
    concurso: DataTypes.STRING,
    candidato: DataTypes.INTEGER,
    email: DataTypes.INTEGER,
    telefone_ddd: DataTypes.INTEGER(2),
    telefone: DataTypes.INTEGER,
    celular_ddd: DataTypes.INTEGER(2),
    celular: DataTypes.INTEGER,
    cep: DataTypes.INTEGER(8),
    cidade: DataTypes.STRING,
    uf: DataTypes.STRING(2),
    bairro: DataTypes.STRING,
    logradouro: DataTypes.STRING,
    complemento: DataTypes.STRING,
    numero: DataTypes.STRING,
    curso: DataTypes.STRING,
    polo: DataTypes.STRING,
    status_prova: DataTypes.STRING,
    status_taxa: DataTypes.STRING,
    status: DataTypes.STRING,
    status_mudanca: DataTypes.DATE,
    desistiu: DataTypes.STRING,
    cancelado: DataTypes.STRING,
    mensalidade: DataTypes.STRING,
    data_vestibular: DataTypes.DATE,
    colaborador_inscricao: DataTypes.STRING,
    colaborador_fatura: DataTypes.STRING,
    ultimo_contato: DataTypes.DATE,
    dias_sem_contato: DataTypes.INTEGER,
    status_atendimento: DataTypes.STRING,
    motivo: DataTypes.STRING,
    observacoes: DataTypes.STRING,
    ultimo_atendimento_colaborador: DataTypes.STRING,
    ultimo_local_atendimento: DataTypes.STRING,
    data_inscricao: DataTypes.DATE,
    data_pre_inscricao: DataTypes.DATE,
    data_retorno: DataTypes.DATE,
    horario_retorno: DataTypes.DATE,
    origem: DataTypes.STRING,
  });

  return preEnrolled;
};
